version: "3.8"

services:
  server:
    build: .
    container_name: server
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 3001
      SERVER_HOST: http://localhost
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSwORD: postgres
      DB_NAME: measure_db

  postgres:
    container_name: postgres_db
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: measure_db
